--柴刀的爱
local cm,m,o=GetID()
function cm.initial_effect(c)
	local e1=Effect.CreateEffect(c)
	e1:SetCategory(CATEGORY_ATKCHANGE)
	e1:SetType(EFFECT_TYPE_ACTIVATE)
	e1:SetCode(EVENT_BATTLE_DESTROYED)
	e1:SetCondition(function(e,tp,eg,ep,ev,re,r,rp)
		local tc=eg:Filter(cm.cfilter,nil,tp):GetFirst()
		if not tc then return false end
		return true
	end)
	e1:SetOperation(function(e,tp,eg,ep,ev,re,r,rp,chk)
		local a=Duel.GetAttacker()
		local d=Duel.GetAttackTarget()
		if a:IsRelateToBattle() or d:IsRelateToBattle() then
			if a:GetControler()==tp then
				local e1=Effect.CreateEffect(e:GetHandler())
				e1:SetType(EFFECT_TYPE_SINGLE)
				e1:SetCode(EFFECT_SET_ATTACK_FINAL)
				e1:SetReset(RESET_EVENT+RESETS_STANDARD+RESET_PHASE+PHASE_END)
				e1:SetValue(a:GetAttack()*2)
				a:RegisterEffect(e1)
				local e2=Effect.CreateEffect(e:GetHandler())
				e2:SetType(EFFECT_TYPE_SINGLE)
				e2:SetCode(EFFECT_EXTRA_ATTACK)
				e2:SetValue(1)
				e2:SetReset(RESET_EVENT+RESETS_STANDARD+RESET_PHASE+PHASE_END)
				a:RegisterEffect(e2)
				local e3=Effect.CreateEffect(e:GetHandler())
				e3:SetType(EFFECT_TYPE_FIELD+EFFECT_TYPE_CONTINUOUS)
				e3:SetCode(EVENT_PHASE+PHASE_BATTLE)
				e3:SetProperty(EFFECT_FLAG_IGNORE_IMMUNE)
				e3:SetCountLimit(1)
				e3:SetOperation(function(e,tp,eg,ep,ev,re,r,rp)
					Duel.SendtoGrave(a,REASON_EFFECT)
				end)
				Duel.RegisterEffect(e3,tp)
			else
				local e1=Effect.CreateEffect(e:GetHandler())
				e1:SetType(EFFECT_TYPE_SINGLE)
				e1:SetCode(EFFECT_SET_ATTACK_FINAL)
				e1:SetReset(RESET_EVENT+RESETS_STANDARD+RESET_PHASE+PHASE_END)
				e1:SetValue(d:GetAttack()*2)
				d:RegisterEffect(e1)
				local e2=Effect.CreateEffect(e:GetHandler())
				e2:SetType(EFFECT_TYPE_SINGLE)
				e2:SetCode(EFFECT_EXTRA_ATTACK)
				e2:SetValue(1)
				e2:SetReset(RESET_EVENT+RESETS_STANDARD+RESET_PHASE+PHASE_END)
				d:RegisterEffect(e2)
				local e3=Effect.CreateEffect(e:GetHandler())
				e3:SetType(EFFECT_TYPE_FIELD+EFFECT_TYPE_CONTINUOUS)
				e3:SetCode(EVENT_PHASE+PHASE_BATTLE)
				e3:SetProperty(EFFECT_FLAG_IGNORE_IMMUNE)
				e3:SetCountLimit(1)
				e3:SetOperation(function(e,tp,eg,ep,ev,re,r,rp)
					Duel.SendtoGrave(d,REASON_EFFECT)
				end)
				Duel.RegisterEffect(e3,tp)
			end
		end
	end)
	c:RegisterEffect(e1)
end
function cm.cfilter(c,tp)
	return c:IsPreviousControler(1-tp)
end