--彩绘轮转窗
local cm,m,o=GetID()
function cm.initial_effect(c)
	c:EnableCounterPermit(0xfd2)
	c:EnableCounterPermit(0xfd3)
	local e1=Effect.CreateEffect(c)
	e1:SetType(EFFECT_TYPE_ACTIVATE)
	e1:SetCode(EVENT_FREE_CHAIN)
	c:RegisterEffect(e1)
	local e2=Effect.CreateEffect(c)
	e2:SetType(EFFECT_TYPE_CONTINUOUS+EFFECT_TYPE_FIELD)
	e2:SetCode(EVENT_CHAIN_SOLVING)
	e2:SetProperty(EFFECT_FLAG_DELAY)
	e2:SetRange(LOCATION_FZONE)
	e2:SetOperation(function(e,tp,eg,ep,ev,re,r,rp)
		local c=re:GetHandler()
		if c~=e:GetHandler() and ep==tp then
			e:GetHandler():AddCounter(0xfd2,1)
		end
	end)
	c:RegisterEffect(e2)
	local e3=e2:Clone()
	e3:SetOperation(function(e,tp,eg,ep,ev,re,r,rp)
		local c=re:GetHandler()
		if c~=e:GetHandler() and ep~=tp then
			e:GetHandler():AddCounter(0xfd3,1)
		end
	end)
	c:RegisterEffect(e3)
	local e4=Effect.CreateEffect(c)
	e4:SetCategory(CATEGORY_DRAW)
	e4:SetType(EFFECT_TYPE_IGNITION)
	e4:SetRange(LOCATION_FZONE)
	e4:SetProperty(EFFECT_FLAG_BOTH_SIDE+EFFECT_FLAG_PLAYER_TARGET)
	e4:SetCountLimit(1,EFFECT_COUNT_CODE_SINGLE)
	e4:SetCost(function(e,tp,eg,ep,ev,re,r,rp,chk)
		if chk==0 then return e:GetHandler():IsCanRemoveCounter(tp,0xfd2,1,REASON_COST) and e:GetHandler():IsCanRemoveCounter(tp,0xfd3,1,REASON_COST) end
		e:GetHandler():RemoveCounter(tp,0xfd2,1,REASON_COST)
		e:GetHandler():RemoveCounter(tp,0xfd3,1,REASON_COST)
	end)
	e4:SetTarget(function(e,tp,eg,ep,ev,re,r,rp,chk)
		if chk==0 then return Duel.IsPlayerCanDraw(tp,1) end
		Duel.SetTargetPlayer(tp)
		Duel.SetTargetParam(1)
		Duel.SetOperationInfo(0,CATEGORY_DRAW,nil,0,tp,1)
		Duel.SetChainLimit(aux.FALSE)
	end)
	e4:SetOperation(function(e,tp,eg,ep,ev,re,r,rp)
		if not e:GetHandler():IsRelateToEffect(e) then return end
		local p,d=Duel.GetChainInfo(0,CHAININFO_TARGET_PLAYER,CHAININFO_TARGET_PARAM)
		Duel.Draw(p,d,REASON_EFFECT)
	end)
	c:RegisterEffect(e4)
end
